[package]
name = "markdownql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
markdown = { version = "1.0.0-alpha.16", features = ["serde"] }
thiserror = "1.0"
rustyline = "14.0.0"
